# BioRob Phase 1A — Final Organized Cleaning + Audit Notebook

This notebook replaces the single long Phase 1A code cell with a clean, cell-by-cell workflow.

**Main fixes included**
1. Uses the correct project path: `/home/tsultan1/BioRob/Human Subject Data`
2. Parses filenames like `067_T116.csv` as `task=1`, `trial=16`
3. Correctly removes slide/media metadata rows such as `StartSlide`, `StartMedia`, `EndMedia`, and `EndSlide`
4. Drops all `EventSource`, `EventSource.1`, `EventSource.2`, `EventSource.3`, etc.
5. Saves per-file and per-subject audit reports
6. Prints `✅ CLEANING APPLIED CORRECTLY` only when required checks pass

In [1]:
# ============================================================
# CELL 1 — Imports and display settings
# This cell loads all packages used for Phase 1A cleaning.
# ============================================================

from pathlib import Path
import re
import json
import warnings
from typing import Optional, Dict, List, Tuple

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 120)
pd.set_option("display.width", 180)

print("✅ Imports loaded successfully.")

✅ Imports loaded successfully.

In [2]:
# ============================================================
# CELL 2 — Project configuration
# This cell defines the BioRob root path and rerun settings.
# ============================================================

ROOT_DIR = Path("/home/tsultan1/BioRob/Human Subject Data")
SUBJECT_GLOB = "Sub-*"

# Final rerun setting:
# True  = overwrite existing cleaned CSVs
# False = skip if cleaned CSV already exists
OVERWRITE_CLEANED = True

# Print one line verdict for every file.
VERBOSE_EACH_FILE = True

# Output reports are saved inside the BioRob project folder.
REPORT_DIR = ROOT_DIR / "_audit_phase1a_cleaning"
REPORT_DIR.mkdir(parents=True, exist_ok=True)

# Expected Neon world-camera field of view used by your original Phase 1A code.
ET_FOV_W = 1600.0
ET_FOV_H = 1200.0

# Keep distances and pupil sizes in millimeters, same as your original code.
KEEP_DIST_IN_MM = True

# Keep raw EMG and drop vendor mV EMG, same as your original code.
KEEP_EMG_RAW = True
DROP_EMG_VENDOR = True

# Drop eyelid features unless you plan to use them downstream.
DROP_EYELID_FEATURES = True

print("ROOT_DIR:", ROOT_DIR)
print("REPORT_DIR:", REPORT_DIR)
print("OVERWRITE_CLEANED:", OVERWRITE_CLEANED)

ROOT_DIR: /home/tsultan1/BioRob/Human Subject Data
REPORT_DIR: /home/tsultan1/BioRob/Human Subject Data/_audit_phase1a_cleaning
OVERWRITE_CLEANED: True

In [3]:
# ============================================================
# CELL 3 — Check project folder and list subjects
# This cell confirms the root folder exists and prints all detected subjects.
# ============================================================

if not ROOT_DIR.exists():
    raise FileNotFoundError(f"ROOT_DIR does not exist: {ROOT_DIR}")

subj_dirs = sorted(
    [p for p in ROOT_DIR.glob(SUBJECT_GLOB) if p.is_dir()],
    key=lambda p: int(re.search(r"Sub[-_ ]*(\d+)", p.name, re.I).group(1)) if re.search(r"Sub[-_ ]*(\d+)", p.name, re.I) else 10**9
)

if not subj_dirs:
    raise RuntimeError(f"No subject folders found under: {ROOT_DIR}")

subject_ids = []
for p in subj_dirs:
    m = re.search(r"Sub[-_ ]*(\d+)", p.name, re.I)
    if m:
        subject_ids.append(int(m.group(1)))

print(f"✅ Found {len(subj_dirs)} subject folders.")
print("Subjects:", [f"Sub-{sid}" for sid in subject_ids])

raw_counts = []
for p in subj_dirs:
    csvs = sorted([x for x in p.glob("*.csv") if x.is_file()])
    raw_counts.append({"subject": p.name, "raw_csv_count": len(csvs)})

raw_count_df = pd.DataFrame(raw_counts)
display(raw_count_df)
print("Total raw CSV files:", int(raw_count_df["raw_csv_count"].sum()))

✅ Found 20 subject folders.
Subjects: ['Sub-1', 'Sub-2', 'Sub-3', 'Sub-5', 'Sub-6', 'Sub-7', 'Sub-8', 'Sub-9', 'Sub-10', 'Sub-11', 'Sub-12', 'Sub-13', 'Sub-14', 'Sub-16', 'Sub-17', 'Sub-19', 'Sub-20', 'Sub-21', 'Sub-22', 'Sub-23']

   subject  raw_csv_count
0    Sub-1             83
1    Sub-2             83
2    Sub-3             83
3    Sub-5             83
4    Sub-6             83
5    Sub-7             83
6    Sub-8             82
7    Sub-9             83
8   Sub-10             83
9   Sub-11             82
10  Sub-12             83
11  Sub-13             83
12  Sub-14             83
13  Sub-16             82
14  Sub-17             83
15  Sub-19             83
16  Sub-20             83
17  Sub-21             83
18  Sub-22             83
19  Sub-23             83

Total raw CSV files: 1657

In [4]:
# ============================================================
# CELL 4 — Constants and required schema checks
# This cell defines expected EEG, EMG, and eye-tracking columns.
# ============================================================

EEG_COLS = [f"Ch{i}" for i in range(1, 9)]

EMG_RAW_COLS = ["Ch1 EMG raw", "Ch2 EMG raw", "Ch3 EMG raw", "Ch4 EMG raw"]
EMG_VENDOR_COLS = ["Ch1 EMG", "Ch2 EMG", "Ch3 EMG", "Ch4 EMG"]

ET_GAZE_2D_COLS = ["ET_GazeLeftx", "ET_GazeLefty", "ET_GazeRightx", "ET_GazeRighty"]
ET_DIST_PUPIL_COLS = ["ET_DistanceLeft", "ET_DistanceRight", "ET_PupilLeft", "ET_PupilRight"]
ET_FLAG_COLS = ["ET_ValidityLeftEye", "ET_ValidityRightEye", "ET_Blink", "ET_Fixation", "ET_Worn"]
ET_IMU_HEAD_COLS = [
    "ET_GyroX", "ET_GyroY", "ET_GyroZ",
    "ET_AccX", "ET_AccY", "ET_AccZ",
    "ET_HeadRotationPitch", "ET_HeadRotationYaw", "ET_HeadRotationRoll",
]
ET_3D_COLS = [
    "ET_Gaze3dEyeballXLeft", "ET_Gaze3dEyeballYLeft", "ET_Gaze3dEyeballZLeft",
    "ET_Gaze3dEyeballXRight", "ET_Gaze3dEyeballYRight", "ET_Gaze3dEyeballZRight",
    "ET_Gaze3dOpticalAxisXLeft", "ET_Gaze3dOpticalAxisYLeft", "ET_Gaze3dOpticalAxisZLeft",
    "ET_Gaze3dOpticalAxisXRight", "ET_Gaze3dOpticalAxisYRight", "ET_Gaze3dOpticalAxisZRight",
    "ET_Gaze3dEyelidAngleTopLeft", "ET_Gaze3dEyelidAngleBottomLeft",
    "ET_Gaze3dEyelidAngleTopRight", "ET_Gaze3dEyelidAngleBottomRight",
    "ET_Gaze3dEyelidApertureLeft", "ET_Gaze3dEyelidApertureRight",
]

ET_EYELID_COLS = [
    "ET_Gaze3dEyelidAngleTopLeft", "ET_Gaze3dEyelidAngleBottomLeft",
    "ET_Gaze3dEyelidAngleTopRight", "ET_Gaze3dEyelidAngleBottomRight",
    "ET_Gaze3dEyelidApertureLeft", "ET_Gaze3dEyelidApertureRight",
]

# Columns that should not remain in cleaned training files.
DROP_COLS_EXACT_BASE = {
    "EventSource", "SlideEvent", "StimType", "Duration",
    "CollectionPhase", "SourceStimuliName",
    "Auto 1 active", "Auto 1 instance",
    "Active active", "active active", "active instance",
    "ET_CameraLeftX", "ET_CameraLeftY", "ET_CameraRightX", "ET_CameraRightY",
}

# Required columns after cleaning.
# If one of these is missing, the file is not considered clean.
REQUIRED_AFTER_CLEAN = (
    ["subject_id", "task", "trial", "Timestamp_seconds"]
    + EEG_COLS
    + EMG_RAW_COLS
    + [
        "ET_TimeSignal",
        "ET_PupilLeft", "ET_PupilRight",
        "ET_DistanceLeft", "ET_DistanceRight",
        "ET_GazeLeftx", "ET_GazeLefty",
        "ET_GazeRightx", "ET_GazeRighty",
        "ET_ValidityLeftEye", "ET_ValidityRightEye",
        "ET_Blink", "ET_Fixation", "ET_Worn",
    ]
)

print("✅ Schema constants are ready.")
print("Required column count:", len(REQUIRED_AFTER_CLEAN))

✅ Schema constants are ready.
Required column count: 30

In [5]:
# ============================================================
# CELL 5 — Filename and header helpers
# This cell fixes the important T116 parsing issue.
# Example: 067_T116.csv -> task=1, trial=16
# ============================================================

TRIAL_RE = re.compile(r"[_\-](?P<kind>[TM])(?P<num>\d+)\.csv$", re.IGNORECASE)

def parse_subject_id(folder_name: str) -> Optional[int]:
    m = re.search(r"Sub[\s\-_]*(\d+)", folder_name, re.IGNORECASE)
    return int(m.group(1)) if m else None

def parse_task_trial(filename: str) -> Tuple[Optional[int], Optional[int]]:
    """
    BioRob convention used here:
      T116 -> task 1, trial 16
      T26  -> task 2, trial 6
      T05  -> task 0, trial 5
    This avoids the old mistake where T116 became task 11, trial 6.
    """
    m = TRIAL_RE.search(filename)
    if not m:
        return None, None

    digits = m.group("num")
    if len(digits) < 2:
        return None, None

    task = int(digits[0])
    trial = int(digits[1:])
    return task, trial

def find_header_row_index(path: Path) -> int:
    """
    Finds the real CSV header row that starts with 'Row,'.
    iMotions/Neon exports often contain metadata lines before the real data table.
    """
    with path.open("r", encoding="utf-8-sig", errors="ignore") as f:
        for i, line in enumerate(f):
            if line.lstrip().startswith("Row,"):
                return i
    raise ValueError(f"Could not find header row starting with 'Row,' in {path}")

def read_raw_imotions_csv(path: Path) -> pd.DataFrame:
    header_idx = find_header_row_index(path)
    df = pd.read_csv(
        path,
        skiprows=header_idx,
        header=0,
        encoding="utf-8-sig",
        engine="python",
        on_bad_lines="skip",
    )
    df.columns = [str(c).strip() for c in df.columns]
    return df

# Test the parser before touching any data.
for ex in ["067_T116.csv", "061_T26.csv", "001_T05.csv", "062_T106.csv"]:
    print(ex, "->", parse_task_trial(ex))

print("✅ Filename parser ready.")

067_T116.csv -> (1, 16)
061_T26.csv -> (2, 6)
001_T05.csv -> (0, 5)
062_T106.csv -> (1, 6)
✅ Filename parser ready.

In [6]:
# ============================================================
# CELL 6 — Cleaning functions
# This cell applies your original Phase 1A cleaning logic with bug fixes.
# ============================================================

def _coerce_numeric(series: pd.Series) -> pd.Series:
    return pd.to_numeric(series, errors="coerce")

def drop_slide_metadata_rows(df: pd.DataFrame) -> Tuple[pd.DataFrame, int]:
    """
    Removes pure metadata/media rows such as StartSlide, StartMedia, EndMedia, EndSlide.

    Important fix:
    The old code checked EventSource != 'SlideEvents', but in your sample file
    EventSource is numeric and SlideEvent contains the actual event names.
    """
    df = df.copy()

    event_mask = pd.Series(False, index=df.index)

    for col in ["SlideEvent", "StimType", "CollectionPhase"]:
        if col in df.columns:
            event_mask |= df[col].notna()

    if "EventSource" in df.columns:
        event_source_str = df["EventSource"].astype(str)
        event_mask |= event_source_str.str.contains("SlideEvents|StartSlide|StartMedia|EndMedia|EndSlide", case=False, na=False)

    # Do not use Timestamp alone as a signal indicator.
    signal_indicator_cols = (
        ["SampleNumber", "ET_TimeSignal", "LSL Timestamp"]
        + EEG_COLS
        + EMG_RAW_COLS
        + ET_GAZE_2D_COLS
        + ET_DIST_PUPIL_COLS
    )
    present_signal_cols = [c for c in signal_indicator_cols if c in df.columns]

    if present_signal_cols:
        signal_present = df[present_signal_cols].notna().any(axis=1)
        drop_mask = event_mask & (~signal_present)
    else:
        drop_mask = event_mask

    removed = int(drop_mask.sum())
    df = df.loc[~drop_mask].copy()
    return df, removed

def make_timestamp_seconds(df: pd.DataFrame) -> Tuple[Optional[pd.Series], str, Dict[str, float]]:
    """
    Builds a master seconds clock while keeping original timing columns.
    Priority follows your original code:
      Timestamp ms -> ET_TimeSignal ms -> LSL Timestamp seconds
    """
    candidates = []
    if "Timestamp" in df.columns:
        candidates.append(("Timestamp", 1000.0))
    if "ET_TimeSignal" in df.columns:
        candidates.append(("ET_TimeSignal", 1000.0))
    if "LSL Timestamp" in df.columns:
        candidates.append(("LSL Timestamp", 1.0))

    for col, denom in candidates:
        s = pd.to_numeric(df[col], errors="coerce")
        if s.notna().any():
            t = s / denom
            first_valid = t.dropna().iloc[0]
            t = (t - first_valid).ffill().bfill()
            dt = t.diff().dropna()
            positive_dt = dt[dt > 0]
            diag = {
                "timestamp_valid_count": int(t.notna().sum()),
                "timestamp_min_s": float(t.min()) if t.notna().any() else np.nan,
                "timestamp_max_s": float(t.max()) if t.notna().any() else np.nan,
                "timestamp_positive_median_dt_s": float(positive_dt.median()) if len(positive_dt) else np.nan,
            }
            return t.astype("float64"), col, diag

    return None, "NONE", {}

def center_emg_raw_inplace(df: pd.DataFrame) -> List[str]:
    """
    Robust-centers raw EMG ADC-like channels by subtracting the channel median.
    This keeps your paper pipeline's raw-EMG policy but removes the ADC baseline.
    """
    logs = []
    for col in EMG_RAW_COLS:
        if col not in df.columns:
            continue
        s = _coerce_numeric(df[col])
        if not s.notna().any():
            df[col] = s.astype("float32")
            logs.append(f"{col}: all NaN")
            continue

        med = float(s.median())
        if 1e4 <= med <= 6e4:
            df[col] = (s - med).astype("float32")
            logs.append(f"{col}: centered by median {med:.2f}")
        else:
            df[col] = s.astype("float32")
            logs.append(f"{col}: not centered; median {med:.2f} not ADC-like")
    return logs

def apply_unit_conversions_inplace(df: pd.DataFrame) -> List[str]:
    """
    Applies unit conversions and dtype tightening:
      - gaze pixel coordinates -> [0,1]
      - pupil/distance kept in mm
      - ET flags -> uint8
      - EEG/EMG/ET numeric channels -> float32
    """
    logs = []

    gaze_denoms = {
        "ET_GazeLeftx": ET_FOV_W,
        "ET_GazeRightx": ET_FOV_W,
        "ET_GazeLefty": ET_FOV_H,
        "ET_GazeRighty": ET_FOV_H,
    }
    for col, denom in gaze_denoms.items():
        if col in df.columns:
            s = _coerce_numeric(df[col])
            df[col] = (s / denom).clip(lower=0.0, upper=1.0).astype("float32")
            logs.append(f"{col}: px -> [0,1]")

    for col in ET_DIST_PUPIL_COLS:
        if col in df.columns:
            s = _coerce_numeric(df[col])
            if KEEP_DIST_IN_MM:
                df[col] = s.astype("float32")
                logs.append(f"{col}: kept as mm")
            else:
                s2 = s.astype("float64")
                mask = s2 >= 0
                s2.loc[mask] = s2.loc[mask] / 1000.0
                df[col] = s2.astype("float32")
                logs.append(f"{col}: mm -> m")

    for col in ET_FLAG_COLS:
        if col in df.columns:
            s = _coerce_numeric(df[col])
            df[col] = (s.fillna(0) > 0.5).astype("uint8")
            logs.append(f"{col}: thresholded to uint8")

    for col in ET_IMU_HEAD_COLS + ET_3D_COLS:
        if col in df.columns:
            df[col] = _coerce_numeric(df[col]).astype("float32")

    for col in EEG_COLS:
        if col in df.columns:
            df[col] = _coerce_numeric(df[col]).astype("float32")

    logs += center_emg_raw_inplace(df)
    return logs

def drop_unneeded_columns(df: pd.DataFrame) -> Tuple[pd.DataFrame, List[str]]:
    """
    Drops metadata/noisy columns and all EventSource variants.
    Important fix: drops EventSource.3 too, not only EventSource.1 and EventSource.2.
    """
    to_drop = set(DROP_COLS_EXACT_BASE)

    if not KEEP_EMG_RAW:
        to_drop.update(EMG_RAW_COLS)
    if DROP_EMG_VENDOR:
        to_drop.update(EMG_VENDOR_COLS)
    if DROP_EYELID_FEATURES:
        to_drop.update(ET_EYELID_COLS)

    for c in df.columns:
        if re.match(r"^EventSource(\.\d+)?$", str(c)):
            to_drop.add(c)
        if str(c).startswith("Unnamed:"):
            to_drop.add(c)

    drop_now = sorted([c for c in to_drop if c in df.columns])
    df = df.drop(columns=drop_now, errors="ignore").copy()
    return df, drop_now

def compact_id_columns(df: pd.DataFrame) -> None:
    for col in ["subject_id", "task", "trial", "SampleNumber", "Row"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).astype("int32")

print("✅ Cleaning functions ready.")

✅ Cleaning functions ready.

In [7]:
# ============================================================
# CELL 7 — Validation function
# This cell checks if cleaning was applied correctly.
# ============================================================

def validate_cleaned_df(df: pd.DataFrame, filename: str) -> Tuple[bool, List[str], List[str], Dict[str, object]]:
    errors = []
    warnings_list = []
    metrics = {}

    metrics["rows_after"] = int(len(df))
    metrics["cols_after"] = int(len(df.columns))

    # Required columns
    missing_required = [c for c in REQUIRED_AFTER_CLEAN if c not in df.columns]
    metrics["missing_required_count"] = len(missing_required)
    metrics["missing_required"] = ";".join(missing_required[:20])
    if missing_required:
        errors.append(f"Missing required columns: {missing_required}")

    # Metadata columns should be gone
    leftover_event_cols = [c for c in df.columns if re.match(r"^EventSource(\.\d+)?$", str(c))]
    leftover_drop_cols = [c for c in df.columns if c in DROP_COLS_EXACT_BASE]
    leftover_bad_cols = leftover_event_cols + leftover_drop_cols
    metrics["leftover_bad_cols"] = ";".join(leftover_bad_cols)
    if leftover_bad_cols:
        errors.append(f"Metadata columns still present: {leftover_bad_cols}")

    # Task/trial sanity
    if "task" in df.columns:
        tasks = sorted(pd.Series(df["task"]).dropna().unique().tolist())
        metrics["tasks"] = str(tasks)
        if any((t < 0 or t > 5) for t in tasks):
            errors.append(f"Task id outside expected 0-5 range: {tasks}")

    if "trial" in df.columns:
        trials = sorted(pd.Series(df["trial"]).dropna().unique().tolist())
        metrics["trials"] = str(trials)

    # Timestamp sanity
    if "Timestamp_seconds" not in df.columns:
        errors.append("Timestamp_seconds missing")
    else:
        t = pd.to_numeric(df["Timestamp_seconds"], errors="coerce")
        metrics["timestamp_nan_count"] = int(t.isna().sum())
        metrics["duration_s"] = float(t.max() - t.min()) if t.notna().any() else np.nan

        dt = t.diff().dropna()
        neg_dt_count = int((dt < -1e-9).sum())
        metrics["timestamp_negative_dt_count"] = neg_dt_count
        if neg_dt_count > 0:
            errors.append(f"Timestamp_seconds is not monotonic; negative dt count={neg_dt_count}")

    # Gaze normalization check
    for col in ET_GAZE_2D_COLS:
        if col in df.columns and df[col].notna().any():
            mn = float(pd.to_numeric(df[col], errors="coerce").min())
            mx = float(pd.to_numeric(df[col], errors="coerce").max())
            metrics[f"{col}_min"] = mn
            metrics[f"{col}_max"] = mx
            if mn < -1e-6 or mx > 1.000001:
                errors.append(f"{col} not normalized to [0,1]: min={mn}, max={mx}")

    # EMG centering check
    for col in EMG_RAW_COLS:
        if col in df.columns and df[col].notna().any():
            med = float(pd.to_numeric(df[col], errors="coerce").median())
            metrics[f"{col}_median_after"] = med
            if abs(med) > 1e-3:
                warnings_list.append(f"{col} median after cleaning is {med:.3f}; check if it was not ADC-like or had unusual values")

    # EEG/EMG/ET coverage warnings
    for group_name, cols in {
        "EEG": EEG_COLS,
        "EMG": EMG_RAW_COLS,
        "ET": ["ET_TimeSignal"] + ET_GAZE_2D_COLS + ET_FLAG_COLS,
    }.items():
        present = [c for c in cols if c in df.columns]
        if present:
            coverage = float(df[present].notna().any(axis=1).mean())
            metrics[f"{group_name}_row_coverage"] = coverage
            if coverage < 0.01:
                warnings_list.append(f"{group_name} coverage is very low: {coverage:.4f}")

    ok = len(errors) == 0
    return ok, errors, warnings_list, metrics

print("✅ Validation function ready.")

✅ Validation function ready.

In [8]:
# ============================================================
# CELL 8 — Clean one file
# This cell combines reading, metadata insertion, cleaning, validation, and saving.
# ============================================================

def clean_one_file(csv_path: Path, save: bool = True) -> Dict[str, object]:
    subj_dir = csv_path.parent
    sid = parse_subject_id(subj_dir.name)
    task, trial = parse_task_trial(csv_path.name)

    if sid is None:
        raise ValueError(f"Could not parse subject id from folder: {subj_dir.name}")
    if task is None or trial is None:
        raise ValueError(f"Could not parse task/trial from filename: {csv_path.name}")

    raw_df = read_raw_imotions_csv(csv_path)
    rows_before = int(len(raw_df))
    cols_before = int(len(raw_df.columns))

    df = raw_df.copy()

    # Insert subject/task/trial at the front.
    for col, val in [("trial", trial), ("task", task), ("subject_id", sid)]:
        if col in df.columns:
            df[col] = val
        else:
            df.insert(0, col, val)

    # Remove pure slide/media rows before timestamp generation.
    df, slide_rows_removed = drop_slide_metadata_rows(df)

    # Add master timestamp immediately after subject/task/trial.
    if "Timestamp_seconds" not in df.columns:
        ts, ts_source, ts_diag = make_timestamp_seconds(df)
        if ts is not None:
            insert_at = 3
            df.insert(insert_at, "Timestamp_seconds", ts.values.astype("float64"))
        else:
            ts_source, ts_diag = "NONE", {}
    else:
        ts_source, ts_diag = "existing", {}

    # Unit conversion and dtype tightening.
    conversion_logs = apply_unit_conversions_inplace(df)

    # Drop unused columns.
    df, dropped_cols = drop_unneeded_columns(df)

    # Compact IDs.
    compact_id_columns(df)

    # Validate.
    ok, errors, warnings_list, metrics = validate_cleaned_df(df, csv_path.name)

    # Save output.
    out_dir = subj_dir / "cleaned"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / csv_path.name

    saved = False
    if save:
        if out_path.exists() and not OVERWRITE_CLEANED:
            saved = False
            warnings_list.append("Output already exists and OVERWRITE_CLEANED=False; file was not overwritten")
        else:
            df.to_csv(out_path, index=False, encoding="utf-8-sig")
            saved = True

    record = {
        "subject": subj_dir.name,
        "subject_id": sid,
        "file": csv_path.name,
        "input_path": str(csv_path),
        "output_path": str(out_path),
        "task": task,
        "trial": trial,
        "rows_before": rows_before,
        "cols_before": cols_before,
        "rows_after": int(len(df)),
        "cols_after": int(len(df.columns)),
        "slide_rows_removed": slide_rows_removed,
        "timestamp_source": ts_source,
        "dropped_cols_count": len(dropped_cols),
        "dropped_cols": ";".join(dropped_cols),
        "saved": bool(saved),
        "ok": bool(ok),
        "errors": " | ".join(errors),
        "warnings": " | ".join(warnings_list),
    }
    record.update(ts_diag)
    record.update(metrics)

    if VERBOSE_EACH_FILE:
        verdict = "✅ CLEANING APPLIED CORRECTLY" if ok else "❌ CLEANING CHECK FAILED"
        print(f"{verdict} | {subj_dir.name}/{csv_path.name} | task={task}, trial={trial} | rows {rows_before}->{len(df)} | saved={saved}")
        if errors:
            print("   Errors:", errors)
        if warnings_list:
            print("   Warnings:", warnings_list[:3])

    return record

print("✅ clean_one_file() ready.")

✅ clean_one_file() ready.

In [9]:
# ============================================================
# CELL 9 — Single-file dry-run check before full rerun
# This cell cleans one raw CSV without saving, so you can inspect the output.
# ============================================================

all_raw_files = []
for subj_dir in subj_dirs:
    all_raw_files.extend(sorted([p for p in subj_dir.glob("*.csv") if p.is_file()]))

if not all_raw_files:
    raise RuntimeError("No raw CSV files found directly inside Sub-* folders.")

# Prefer a T116 file if present, because this catches the old parsing mistake.
preferred = [p for p in all_raw_files if re.search(r"_T116\.csv$", p.name, re.I)]
sample_file = preferred[0] if preferred else all_raw_files[0]

print("Sample file selected:", sample_file)

sample_record = clean_one_file(sample_file, save=False)

print("\nSingle-file audit record:")
display(pd.DataFrame([sample_record]).T)

print("\n✅ Single-file dry-run finished. If the verdict above is correct, run the batch cell next.")

Sample file selected: /home/tsultan1/BioRob/Human Subject Data/Sub-1/034_T116.csv
✅ CLEANING APPLIED CORRECTLY | Sub-1/034_T116.csv | task=1, trial=16 | rows 19034->19030 | saved=False

Single-file audit record:

                                                                                0
subject                                                                     Sub-1
subject_id                                                                      1
file                                                                 034_T116.csv
input_path                      /home/tsultan1/BioRob/Human Subject Data/Sub-1...
output_path                     /home/tsultan1/BioRob/Human Subject Data/Sub-1...
task                                                                            1
trial                                                                          16
rows_before                                                                 19034
cols_before                                                                    74
rows_after                                                                  19030
cols_after                                                                     55
slide_rows_removed                                                              4
timestamp_source                                                        Timestamp
dropped_cols_count                                                             23
dropped_cols                    Ch1 EMG;Ch2 EMG;Ch3 EMG;Ch4 EMG;CollectionPhas...
saved                                                                       False
ok                                                                           True
errors
warnings
timestamp_valid_count                                                       19030
timestamp_min_s                                                               0.0
timestamp_max_s                                                         13.739181
timestamp_positive_median_dt_s                                           0.000194
missing_required_count                                                          0
missing_required
leftover_bad_cols
tasks                                                                         [1]
trials                                                                       [16]
timestamp_nan_count                                                             0
duration_s                                                              13.739181
timestamp_negative_dt_count                                                     0
ET_GazeLeftx_min                                                         0.304375
ET_GazeLeftx_max                                                          0.65875
ET_GazeLefty_min                                                         0.394167
ET_GazeLefty_max                                                         0.760833
ET_GazeRightx_min                                                        0.304375
ET_GazeRightx_max                                                         0.65875
ET_GazeRighty_min                                                        0.394167
ET_GazeRighty_max                                                        0.760833
Ch1 EMG raw_median_after                                                      0.0
Ch2 EMG raw_median_after                                                      0.0
Ch3 EMG raw_median_after                                                      0.0
Ch4 EMG raw_median_after                                                      0.0
EEG_row_coverage                                                         0.528797
EMG_row_coverage                                                         0.360641
ET_row_coverage                                                               1.0

✅ Single-file dry-run finished. If the verdict above is correct, run the batch cell next.

In [10]:
# ============================================================
# CELL 10 — Full batch cleaning for all subjects
# This cell reruns Phase 1A for every raw CSV in every Sub-* folder.
# ============================================================

audit_records = []
failed_files = []

print(f"Starting full Phase 1A cleaning on {len(all_raw_files)} raw files...")
print("OVERWRITE_CLEANED:", OVERWRITE_CLEANED)

for csv_path in all_raw_files:
    try:
        rec = clean_one_file(csv_path, save=True)
        audit_records.append(rec)
        if not rec["ok"]:
            failed_files.append(rec)
    except Exception as e:
        err_rec = {
            "subject": csv_path.parent.name,
            "file": csv_path.name,
            "input_path": str(csv_path),
            "ok": False,
            "saved": False,
            "errors": repr(e),
        }
        audit_records.append(err_rec)
        failed_files.append(err_rec)
        print(f"❌ ERROR | {csv_path.parent.name}/{csv_path.name}: {e}")

audit_df = pd.DataFrame(audit_records)
audit_path = REPORT_DIR / "phase1a_cleaning_audit.csv"
audit_df.to_csv(audit_path, index=False)

failed_df = pd.DataFrame(failed_files)
failed_path = REPORT_DIR / "phase1a_failed_files.csv"
failed_df.to_csv(failed_path, index=False)

print("\n============================================================")
print("PHASE 1A BATCH CLEANING SUMMARY")
print("============================================================")
print("Total files processed:", len(audit_df))
print("Files passed:", int(audit_df["ok"].fillna(False).sum()) if "ok" in audit_df.columns else 0)
print("Files failed:", len(failed_df))
print("Audit saved to:", audit_path)
print("Failed-file report saved to:", failed_path)

if len(failed_df) == 0:
    print("✅ ALL PHASE 1A FILES CLEANED CORRECTLY")
else:
    print("❌ SOME FILES FAILED. Displaying failed files:")
    cols = ["subject", "file", "errors"]
    if "warnings" in failed_df.columns:
        cols.append("warnings")
    display(failed_df[cols])

Starting full Phase 1A cleaning on 1657 raw files...
OVERWRITE_CLEANED: True
✅ CLEANING APPLIED CORRECTLY | Sub-1/001_T03.csv | task=0, trial=3 | rows 16791->16787 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/002_T516.csv | task=5, trial=16 | rows 14139->14135 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/003_T515.csv | task=5, trial=15 | rows 17460->17456 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/004_T514.csv | task=5, trial=14 | rows 14955->14951 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/005_T513.csv | task=5, trial=13 | rows 15423->15419 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/006_T512.csv | task=5, trial=12 | rows 17492->17488 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/007_T511.csv | task=5, trial=11 | rows 17113->17109 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/008_T510.csv | task=5, trial=10 | rows 16579->16575 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/009_T59.csv | task=5, trial=9 | rows 12619->12615 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/010_T416.csv | task=4, trial=16 | rows 16081->16077 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/011_T415.csv | task=4, trial=15 | rows 15583->15579 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/012_T414.csv | task=4, trial=14 | rows 17664->17660 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/013_T413.csv | task=4, trial=13 | rows 16117->16113 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/014_T412.csv | task=4, trial=12 | rows 17262->17258 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/015_T411.csv | task=4, trial=11 | rows 16495->16491 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/016_T410.csv | task=4, trial=10 | rows 13682->13678 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/017_T49.csv | task=4, trial=9 | rows 14548->14544 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/018_T316.csv | task=3, trial=16 | rows 15505->15501 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/019_T315.csv | task=3, trial=15 | rows 17304->17300 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/020_T314.csv | task=3, trial=14 | rows 17474->17470 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/021_T313.csv | task=3, trial=13 | rows 16258->16254 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/022_T312.csv | task=3, trial=12 | rows 14817->14813 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/023_T311.csv | task=3, trial=11 | rows 15270->15266 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/024_T310.csv | task=3, trial=10 | rows 13993->13989 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/025_T39.csv | task=3, trial=9 | rows 16512->16508 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/026_T216.csv | task=2, trial=16 | rows 16531->16527 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/027_T215.csv | task=2, trial=15 | rows 20274->20270 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/028_T214.csv | task=2, trial=14 | rows 20521->20517 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/029_T213.csv | task=2, trial=13 | rows 18104->18100 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/030_T212.csv | task=2, trial=12 | rows 20176->20172 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/031_T211.csv | task=2, trial=11 | rows 20258->20254 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/032_T210.csv | task=2, trial=10 | rows 20697->20693 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/033_T29.csv | task=2, trial=9 | rows 18635->18631 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/034_T116.csv | task=1, trial=16 | rows 19034->19030 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/035_T115.csv | task=1, trial=15 | rows 17077->17073 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/036_T114.csv | task=1, trial=14 | rows 17978->17976 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/037_T113.csv | task=1, trial=13 | rows 16407->16403 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/038_T112.csv | task=1, trial=12 | rows 19535->19531 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/039_T111.csv | task=1, trial=11 | rows 18300->18296 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/040_T110.csv | task=1, trial=10 | rows 16811->16807 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/041_T19.csv | task=1, trial=9 | rows 17078->17074 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/042_T02.csv | task=0, trial=2 | rows 14610->14606 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/043_T58.csv | task=5, trial=8 | rows 15477->15473 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/044_T57.csv | task=5, trial=7 | rows 15963->15959 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/045_T56.csv | task=5, trial=6 | rows 17084->17080 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/046_T55.csv | task=5, trial=5 | rows 15983->15979 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/047_T54.csv | task=5, trial=4 | rows 14566->14562 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/048_T53.csv | task=5, trial=3 | rows 17240->17236 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/049_T52.csv | task=5, trial=2 | rows 13858->13854 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/050_T51.csv | task=5, trial=1 | rows 15545->15541 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/051_T48.csv | task=4, trial=8 | rows 18510->18506 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/052_T47.csv | task=4, trial=7 | rows 18376->18372 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/053_T46.csv | task=4, trial=6 | rows 17319->17315 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/054_T45.csv | task=4, trial=5 | rows 17532->17528 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/055_T44.csv | task=4, trial=4 | rows 18155->18151 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/056_T43.csv | task=4, trial=3 | rows 18531->18527 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/057_T42.csv | task=4, trial=2 | rows 17868->17864 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/058_T41.csv | task=4, trial=1 | rows 16242->16238 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/059_T38.csv | task=3, trial=8 | rows 16625->16621 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/060_T37.csv | task=3, trial=7 | rows 17760->17756 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/061_T36.csv | task=3, trial=6 | rows 15613->15609 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/062_T35.csv | task=3, trial=5 | rows 15169->15165 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/063_T34.csv | task=3, trial=4 | rows 17342->17338 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/064_T33.csv | task=3, trial=3 | rows 14465->14461 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/065_T32.csv | task=3, trial=2 | rows 17613->17609 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/066_T31.csv | task=3, trial=1 | rows 13938->13934 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/067_T28.csv | task=2, trial=8 | rows 21134->21130 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/068_T27.csv | task=2, trial=7 | rows 19024->19020 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/069_T26.csv | task=2, trial=6 | rows 19844->19840 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/070_T25.csv | task=2, trial=5 | rows 20096->20092 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/071_T24.csv | task=2, trial=4 | rows 21405->21401 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/072_T23.csv | task=2, trial=3 | rows 22061->22057 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/073_T22.csv | task=2, trial=2 | rows 19322->19318 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/074_T21.csv | task=2, trial=1 | rows 21099->21095 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/075_T18.csv | task=1, trial=8 | rows 18233->18229 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/076_T17.csv | task=1, trial=7 | rows 17923->17919 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/077_T16.csv | task=1, trial=6 | rows 16974->16970 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/078_T15.csv | task=1, trial=5 | rows 16273->16269 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/079_T14.csv | task=1, trial=4 | rows 19513->19509 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/080_T13.csv | task=1, trial=3 | rows 17464->17460 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/081_T12.csv | task=1, trial=2 | rows 16399->16395 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/082_T11.csv | task=1, trial=1 | rows 15965->15961 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-1/083_T01.csv | task=0, trial=1 | rows 24878->24874 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/001_T03.csv | task=0, trial=3 | rows 25565->25561 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/002_T516.csv | task=5, trial=16 | rows 20263->20259 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/003_T515.csv | task=5, trial=15 | rows 18620->18616 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/004_T514.csv | task=5, trial=14 | rows 20297->20293 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/005_T513.csv | task=5, trial=13 | rows 22552->22548 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/006_T512.csv | task=5, trial=12 | rows 20304->20300 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/007_T511.csv | task=5, trial=11 | rows 18150->18146 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/008_T510.csv | task=5, trial=10 | rows 17265->17261 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/009_T59.csv | task=5, trial=9 | rows 21139->21135 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/010_T58.csv | task=5, trial=8 | rows 17620->17616 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/011_T57.csv | task=5, trial=7 | rows 21559->21555 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/012_T56.csv | task=5, trial=6 | rows 18537->18533 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/013_T55.csv | task=5, trial=5 | rows 17600->17596 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/014_T54.csv | task=5, trial=4 | rows 22205->22201 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/015_T53.csv | task=5, trial=3 | rows 20901->20897 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/016_T52.csv | task=5, trial=2 | rows 19035->19031 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/017_T51.csv | task=5, trial=1 | rows 19591->19587 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/018_T416.csv | task=4, trial=16 | rows 23942->23938 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/019_T415.csv | task=4, trial=15 | rows 19427->19423 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/020_T414.csv | task=4, trial=14 | rows 22168->22164 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/021_T413.csv | task=4, trial=13 | rows 23178->23174 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/022_T412.csv | task=4, trial=12 | rows 20470->20466 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/023_T411.csv | task=4, trial=11 | rows 23960->23956 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/024_T410.csv | task=4, trial=10 | rows 20589->20585 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/025_T49.csv | task=4, trial=9 | rows 26324->26320 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/026_T48.csv | task=4, trial=8 | rows 21811->21807 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/027_T47.csv | task=4, trial=7 | rows 24586->24582 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/028_T46.csv | task=4, trial=6 | rows 22656->22652 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/029_T45.csv | task=4, trial=5 | rows 22212->22208 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/030_T44.csv | task=4, trial=4 | rows 21176->21172 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/031_T43.csv | task=4, trial=3 | rows 21912->21908 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/032_T42.csv | task=4, trial=2 | rows 21370->21366 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/033_T41.csv | task=4, trial=1 | rows 22283->22279 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/034_T02.csv | task=0, trial=2 | rows 27595->27591 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/035_T316.csv | task=3, trial=16 | rows 20125->20121 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/036_T315.csv | task=3, trial=15 | rows 21063->21059 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/037_T314.csv | task=3, trial=14 | rows 21775->21771 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/038_T313.csv | task=3, trial=13 | rows 21602->21598 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/039_T312.csv | task=3, trial=12 | rows 20532->20528 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/040_T311.csv | task=3, trial=11 | rows 20384->20380 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/041_T310.csv | task=3, trial=10 | rows 21836->21832 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/042_T39.csv | task=3, trial=9 | rows 21356->21352 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/043_T38.csv | task=3, trial=8 | rows 21491->21487 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/044_T37.csv | task=3, trial=7 | rows 20346->20342 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/045_T36.csv | task=3, trial=6 | rows 19611->19607 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/046_T35.csv | task=3, trial=5 | rows 20127->20123 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/047_T34.csv | task=3, trial=4 | rows 18370->18366 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/048_T33.csv | task=3, trial=3 | rows 20916->20912 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/049_T32.csv | task=3, trial=2 | rows 20721->20717 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/050_T31.csv | task=3, trial=1 | rows 20224->20220 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/051_T216.csv | task=2, trial=16 | rows 24402->24398 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/052_T215.csv | task=2, trial=15 | rows 25510->25506 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/053_T214.csv | task=2, trial=14 | rows 24325->24321 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/054_T213.csv | task=2, trial=13 | rows 23848->23844 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/055_T212.csv | task=2, trial=12 | rows 22489->22485 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/056_T211.csv | task=2, trial=11 | rows 23855->23851 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/057_T210.csv | task=2, trial=10 | rows 24184->24180 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/058_T29.csv | task=2, trial=9 | rows 25544->25540 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/059_T28.csv | task=2, trial=8 | rows 25485->25481 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/060_T27.csv | task=2, trial=7 | rows 22352->22349 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/061_T26.csv | task=2, trial=6 | rows 23525->23521 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/062_T25.csv | task=2, trial=5 | rows 27730->27726 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/063_T24.csv | task=2, trial=4 | rows 24135->24131 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/064_T23.csv | task=2, trial=3 | rows 23509->23505 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/065_T22.csv | task=2, trial=2 | rows 26374->26370 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/066_T21.csv | task=2, trial=1 | rows 21853->21849 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/067_T116.csv | task=1, trial=16 | rows 24462->24458 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/068_T115.csv | task=1, trial=15 | rows 23109->23105 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/069_T114.csv | task=1, trial=14 | rows 24340->24336 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/070_T113.csv | task=1, trial=13 | rows 22551->22547 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/071_T112.csv | task=1, trial=12 | rows 19438->19434 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/072_T111.csv | task=1, trial=11 | rows 20049->20045 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/073_T110.csv | task=1, trial=10 | rows 21090->21086 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/074_T19.csv | task=1, trial=9 | rows 23007->23003 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/075_T18.csv | task=1, trial=8 | rows 19921->19917 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/076_T17.csv | task=1, trial=7 | rows 21220->21216 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/077_T16.csv | task=1, trial=6 | rows 22392->22388 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/078_T15.csv | task=1, trial=5 | rows 20100->20096 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/079_T14.csv | task=1, trial=4 | rows 19630->19626 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/080_T13.csv | task=1, trial=3 | rows 20425->20421 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/081_T12.csv | task=1, trial=2 | rows 20072->20068 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/082_T11.csv | task=1, trial=1 | rows 18082->18078 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-2/083_T01.csv | task=0, trial=1 | rows 35017->35013 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/001_T03.csv | task=0, trial=3 | rows 16027->16023 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/002_T516.csv | task=5, trial=16 | rows 17073->17069 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/003_T515.csv | task=5, trial=15 | rows 16317->16313 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/004_T514.csv | task=5, trial=14 | rows 16333->16329 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/005_T513.csv | task=5, trial=13 | rows 14817->14813 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/006_T512.csv | task=5, trial=12 | rows 16099->16095 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/007_T511.csv | task=5, trial=11 | rows 15757->15753 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/008_T510.csv | task=5, trial=10 | rows 15956->15952 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/009_T59.csv | task=5, trial=9 | rows 15402->15398 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/010_T58.csv | task=5, trial=8 | rows 16982->16978 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/011_T57.csv | task=5, trial=7 | rows 16110->16106 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/012_T56.csv | task=5, trial=6 | rows 15404->15400 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/013_T55.csv | task=5, trial=5 | rows 15178->15174 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/014_T54.csv | task=5, trial=4 | rows 15812->15808 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/015_T53.csv | task=5, trial=3 | rows 16477->16473 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/016_T52.csv | task=5, trial=2 | rows 16346->16342 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/017_T51.csv | task=5, trial=1 | rows 16556->16552 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/018_T416.csv | task=4, trial=16 | rows 19644->19640 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/019_T415.csv | task=4, trial=15 | rows 18383->18379 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/020_T414.csv | task=4, trial=14 | rows 17558->17554 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/021_T413.csv | task=4, trial=13 | rows 19139->19135 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/022_T412.csv | task=4, trial=12 | rows 19442->19438 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/023_T411.csv | task=4, trial=11 | rows 19556->19552 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/024_T410.csv | task=4, trial=10 | rows 18247->18243 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/025_T49.csv | task=4, trial=9 | rows 17900->17896 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/026_T48.csv | task=4, trial=8 | rows 19244->19240 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/027_T47.csv | task=4, trial=7 | rows 18144->18140 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/028_T46.csv | task=4, trial=6 | rows 18943->18939 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/029_T45.csv | task=4, trial=5 | rows 20507->20503 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/030_T44.csv | task=4, trial=4 | rows 20708->20704 | saved=True
✅ CLEANING APPLIED CORRECTLY | Sub-3/031_T43.csv | task=4, trial=3 | rows 19525->19521 | saved=True

    subject          file                                             errors warnings
0     Sub-3  071_T112.csv  Missing required columns: ['ET_ValidityLeftEye...
1     Sub-6  036_T315.csv  Missing required columns: ['ET_ValidityLeftEye...
2     Sub-6    074_T9.csv  ValueError('Could not parse task/trial from fi...      NaN
3     Sub-7  038_T313.csv  Missing required columns: ['ET_ValidityLeftEye...
4     Sub-8  006_T512.csv  Missing required columns: ['ET_ValidityLeftEye...
..      ...           ...                                                ...      ...
100  Sub-22   011_T57.csv  Missing required columns: ['ET_ValidityLeftEye...
101  Sub-22   029_T45.csv  Missing required columns: ['ET_ValidityLeftEye...
102  Sub-23  039_T312.csv  Missing required columns: ['ET_ValidityLeftEye...
103  Sub-23  055_T212.csv  Missing required columns: ['ET_ValidityLeftEye...
104  Sub-23   081_T12.csv  Missing required columns: ['ET_ValidityLeftEye...

[105 rows x 4 columns]

In [11]:
# ============================================================
# CELL 11 — Subject-level summary after cleaning
# This cell summarizes cleaned files per subject and important sanity metrics.
# ============================================================

if "audit_df" not in globals():
    audit_path = REPORT_DIR / "phase1a_cleaning_audit.csv"
    audit_df = pd.read_csv(audit_path)

summary = (
    audit_df
    .groupby(["subject", "subject_id"], dropna=False)
    .agg(
        files=("file", "count"),
        passed=("ok", lambda x: int(pd.Series(x).fillna(False).sum())),
        failed=("ok", lambda x: int((~pd.Series(x).fillna(False).astype(bool)).sum())),
        min_task=("task", "min"),
        max_task=("task", "max"),
        min_trial=("trial", "min"),
        max_trial=("trial", "max"),
        total_rows_after=("rows_after", "sum"),
    )
    .reset_index()
    .sort_values("subject_id")
)

summary_path = REPORT_DIR / "phase1a_subject_summary.csv"
summary.to_csv(summary_path, index=False)

print("Subject summary saved to:", summary_path)
display(summary)

if int(summary["failed"].sum()) == 0:
    print("✅ SUBJECT-LEVEL CHECK PASSED")
else:
    print("❌ SUBJECT-LEVEL CHECK FAILED")

Subject summary saved to: /home/tsultan1/BioRob/Human Subject Data/_audit_phase1a_cleaning/phase1a_subject_summary.csv

   subject  subject_id  files  passed  failed  min_task  max_task  min_trial  max_trial  total_rows_after
0    Sub-1         1.0     83      83       0       0.0       5.0        1.0       16.0         1433213.0
9    Sub-2         2.0     83      83       0       0.0       5.0        1.0       16.0         1821035.0
14   Sub-3         3.0     83      82       1       0.0       5.0        1.0       16.0         1566913.0
15   Sub-5         5.0     83      83       0       0.0       5.0        1.0       16.0         1167859.0
16   Sub-6         6.0     82      81       1       0.0       5.0        1.0       16.0         1107863.0
18   Sub-7         7.0     83      82       1       0.0       5.0        1.0       16.0         1240719.0
19   Sub-8         8.0     82      80       2       0.0       5.0        1.0       16.0         1162734.0
20   Sub-9         9.0     83      82       1       0.0       5.0        1.0       16.0         1110037.0
1   Sub-10        10.0     83      82       1       0.0       5.0        1.0       16.0         1180669.0
2   Sub-11        11.0     82      80       2       0.0       5.0        1.0       16.0         1027067.0
3   Sub-12        12.0     83      81       2       0.0       5.0        1.0       16.0         1274442.0
4   Sub-13        13.0     83       0      83       0.0       5.0        1.0       16.0         1248580.0
5   Sub-14        14.0     83      82       1       0.0       5.0        1.0       16.0          968557.0
6   Sub-16        16.0     82      80       2       0.0       5.0        1.0       16.0          978157.0
7   Sub-17        17.0     83      83       0       0.0       5.0        1.0       16.0          957259.0
8   Sub-19        19.0     83      83       0       0.0       5.0        1.0       16.0         1035088.0
10  Sub-20        20.0     83      83       0       0.0       5.0        1.0       17.0         1002375.0
11  Sub-21        21.0     83      81       2       0.0       5.0        1.0       16.0          943919.0
12  Sub-22        22.0     83      81       2       0.0       5.0        1.0       16.0          942179.0
13  Sub-23        23.0     83      80       3       0.0       5.0        1.0       16.0          879604.0
17   Sub-6         NaN      1       0       1       NaN       NaN        NaN        NaN               0.0

❌ SUBJECT-LEVEL CHECK FAILED

In [12]:
# ============================================================
# CELL 12 — Verify cleaned folders and cleaned CSV existence
# This cell physically checks that cleaned CSV files exist on disk.
# ============================================================

exist_records = []

for _, row in audit_df.iterrows():
    out_path = Path(row["output_path"]) if "output_path" in row and pd.notna(row["output_path"]) else None
    exists = out_path.exists() if out_path is not None else False
    exist_records.append({
        "subject": row.get("subject"),
        "file": row.get("file"),
        "output_path": str(out_path) if out_path is not None else "",
        "exists": exists,
        "ok": bool(row.get("ok", False)),
    })

exist_df = pd.DataFrame(exist_records)
missing_outputs = exist_df[(exist_df["ok"] == True) & (exist_df["exists"] == False)]

exist_path = REPORT_DIR / "phase1a_output_existence_check.csv"
exist_df.to_csv(exist_path, index=False)

print("Output existence report saved to:", exist_path)
print("Cleaned outputs missing for passed files:", len(missing_outputs))

if len(missing_outputs) == 0:
    print("✅ CLEANED CSV FILES EXIST ON DISK")
else:
    print("❌ Some passed files do not have saved outputs:")
    display(missing_outputs)

Output existence report saved to: /home/tsultan1/BioRob/Human Subject Data/_audit_phase1a_cleaning/phase1a_output_existence_check.csv
Cleaned outputs missing for passed files: 0
✅ CLEANED CSV FILES EXIST ON DISK

In [13]:
# ============================================================
# CELL 13 — Save final cleaned schema
# This cell saves the final column order from one cleaned file for reproducibility.
# ============================================================

passed = audit_df[audit_df["ok"] == True].copy()
if len(passed) == 0:
    raise RuntimeError("No passed cleaned files found; cannot save schema.")

first_out = Path(passed.iloc[0]["output_path"])
schema_df = pd.read_csv(first_out, nrows=5)
schema = {
    "example_file": str(first_out),
    "n_columns": len(schema_df.columns),
    "columns": list(schema_df.columns),
}

schema_path = REPORT_DIR / "phase1a_cleaned_schema.json"
with open(schema_path, "w", encoding="utf-8") as f:
    json.dump(schema, f, indent=2)

print("Schema saved to:", schema_path)
print("Number of columns:", schema["n_columns"])
print("First 30 columns:")
print(schema["columns"][:30])

print("\n✅ PHASE 1A FINAL CLEANING PIPELINE COMPLETE")

Schema saved to: /home/tsultan1/BioRob/Human Subject Data/_audit_phase1a_cleaning/phase1a_cleaned_schema.json
Number of columns: 55
First 30 columns:
['subject_id', 'task', 'trial', 'Timestamp_seconds', 'Row', 'Timestamp', 'SampleNumber', 'Ch1 EMG raw', 'Ch2 EMG raw', 'Ch3 EMG raw', 'Ch4 EMG raw', 'ET_TimeSignal', 'ET_PupilLeft', 'ET_PupilRight', 'ET_DistanceLeft', 'ET_DistanceRight', 'ET_GazeLeftx', 'ET_GazeLefty', 'ET_GazeRightx', 'ET_GazeRighty', 'ET_ValidityLeftEye', 'ET_ValidityRightEye', 'ET_GyroX', 'ET_GyroY', 'ET_GyroZ', 'ET_AccX', 'ET_AccY', 'ET_AccZ', 'ET_HeadRotationPitch', 'ET_HeadRotationYaw']

✅ PHASE 1A FINAL CLEANING PIPELINE COMPLETE